name: Clippy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Cargo clippy
        id: cargo_clippy
        run: |
          cargo clippy --release
